{
  "name": "redux-thunk-error-handler",
  "version": "1.1.4",
  "description": "An error handler for thunks that, when used in conjunction with `redux-thunk-recursion-detect` can handle errors thrown in both async and sync thunks gracefully.",
  "main": "dist/reduxThunkErrorHandler.cjs.js",
  "module": "dist/reduxThunkErrorHandler.esm.js",
  "repository": "github:itaylor/thunk-centric-redux",
  "files": [
    "dist",
    "index.d.ts"
  ],
  "types": "index.d.ts",
  "scripts": {
    "build": "node node_modules/.bin/rollup -c",
    "dev": "node node_modules/.bin/rollup -c -w",
    "test": "NODE_ENV=test node node_modules/.bin/jest && yarn test:mocha",
    "test:mocha": "NODE_ENV=test node node_modules/.bin/mocha --require @babel/register --ui tdd src/*.mochaTest.js",
    "pretest": "yarn run build",
    "coverage": "node node_modules/.bin/jest --coverage",
    "precoverage": "yarn run build"
  },
  "keywords": [
    "redux",
    "thunk",
    "error",
    "handler",
    "catch",
    "async",
    "dispatch",
    "exception",
    "promise",
    "reject"
  ],
  "author": "ian.b.taylor@gmail.com",
  "license": "MIT",
  "peerDependencies": {
    "redux": "^4.0.3"
  },
  "devDependencies": {
    "@babel/register": "^7.4.4",
    "expect": "^24.8.0",
    "jest": "^24.8.0",
    "mocha": "^6.1.4",
    "redux": "^4.0.3",
    "rollup": "^1.15.3"
  },
  "dependencies": {
    "redux-thunk-recursion-detect": "1.1.1"
  }
}
